name: PR Validation

on: [ pull_request ]

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm run lint
      - name: Run Biome
        run: pnpm run biome:check
      - name: Build
        run: pnpm run build

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Unit tests
        run: pnpm run test:unit:ci
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-unit
          path: playwright-report/
          retention-days: 30

  visual-regression:
    name: Visual tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Build
        run: pnpm run build
      - name: Visual regression tests
        run: pnpm run test:visual
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-component
          path: playwright-report/
          retention-days: 30
