name: PR Validation

on: [ pull_request ]

jobs:
  static-analysis:
    name: Static analysis
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm run ci -- --ignore-scripts
      - name: Run ESLint
        run: npm run lint
      - name: Build
        run: npm run build

  unit:
    name: Unit tests
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use latest stable Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install dependencies
        run: npm run ci -- --ignore-scripts
      - name: Unit tests
        run: npm run test:unit:ci

  visual-regression:
    name: Visual tests
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use latest stable Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install dependencies
        run: npm run ci -- --ignore-scripts
      - name: Build
        run: npm run build
      - name: Visual regression tests
        run: npm run test:visual:ci
      - name: Save visual regression tests artifacts (on failure)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: .loki
          path: .loki/
          retention-days: 5
