name: PR Validation

on: [ pull_request ]

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm run ci -- --ignore-scripts
      - name: Run ESLint
        run: npm run lint
      - name: Build
        run: npm run build

  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Use latest stable Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install dependencies
        run: npm run ci -- --ignore-scripts
      - name: Unit tests
        run: npm run test:unit:ci

  visual-regression:
    name: Visual tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Use latest stable Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install dependencies
        run: npm run ci -- --ignore-scripts
      - name: Build
        run: npm run build
      - name: Visual regression tests
        run: npm run test:visual:ci
      - name: Save visual regression tests artifacts (on failure)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: .loki
          path: .loki/
          retention-days: 5
