name: Update Snaphots

on:
  workflow_dispatch:

jobs:
  update-snaphots:
    name: Update Visual Tests snaphots
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Build
        run: pnpm run build
      - name: Visual regression tests
        run: pnpm run test:visual -- --update-snapshots
      - name: Copy modified snapshots
        run: |
          git ls-files --other --modified --exclude-standard | grep '^test-components/__snapshots__/' | while IFS= read -r file; do
            mkdir -p "updated_snapshots/$(dirname "$file")"
            cp "$file" "updated_snapshots/$file"
          done
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: snapshots
          path: updated_snapshots/
          retention-days: 20
